@MiniShop_HostAddress = http://localhost:5199

GET {{MiniShop_HostAddress}}/weatherforecast/
Accept: application/json

###
PUT https://localhost:7053/api/products/2
Content-Type: application/json

{
  "name": "Gaming Mouse",
  "description": "Wireless RGB Gaming Mouse",
  "price": 1499,
  "stock": 30
}

###
DELETE https://localhost:7053/api/products/2

###
GET https://localhost:7053/api/products 
###
POST https://localhost:7053/api/products
Content-Type: application/json

{
  "name": "Laptop",
  "description": "Gaming laptop",
  "price": 65000,
  "stock": 10,
  "categoryId": 1
}