@MiniShop_HostAddress = http://localhost:5199

GET {{MiniShop_HostAddress}}/weatherforecast/
Accept: application/json

###
GET https://localhost:7053/api/orders

###
DELETE https://localhost:7053/api/cart/items/1

###
GET https://localhost:7053/api/products/6
###
GET https://localhost:7053/api/cart
###
POST https://localhost:7053/api/cart/items
Content-Type: application/json

{
  "productId": 6,
  "quantity": 2
}

###
POST https://localhost:7053/api/orders/checkout

###
POST https://localhost:7053/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@minishop.com",
  "password": "Password123"
}